[package]
name = "scrolex"
version = "0.1.0-deb+4"
edition = "2021"
authors = ["Andrii Berezhynskyi <microsolutions_harebrain@aleeas.com>"]
license = "MIT"
homepage = "https://github.com/molecule-man/scrolex"
repository = "https://github.com/molecule-man/scrolex"
description = "A Horizontally Scrolled PDF Viewer"

[dependencies]
futures = "0.3.30"
gtk = { version = "0.9.1", package = "gtk4", features = ["v4_14"] }
once_cell = "1.19.0"
poppler-rs = "0.24.1"
poppler-sys-rs = "0.24.0"

[build-dependencies]
glib-build-tools = "0.20.0"

[profile.deb]
inherits = "release"
debug = false

[package.metadata.deb]
assets = [
	["target/release/scrolex", "usr/bin/", "755"],
	["resources/scrolex.desktop", "usr/share/applications/", "644"],
	["resources/icon.png", "usr/share/icons/scrolex.png", "644"]
]
