[package]
name = "pdf_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
gtk = { version = "0.9.1", package = "gtk4", features = ["v4_14"] }
poppler-rs = "0.24.1"

[build-dependencies]
glib-build-tools = "0.20.0"
