name: ci
on:
  push:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  test:
    name: test
    env:
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            rust: stable
          # - os: ubuntu-24.04
          #   rust: nightly
          # - os: windows
          #   rust: stable
          # - os: windows
          #   rust: nightly

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-24.04'
      run: |
        ci/ubuntu-install-packages

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: xvfb-run --auto-servernum cargo test --verbose
