name: ci
on:
  push:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  test:
    name: test
    env:
      RUST_BACKTRACE: 1
      PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
          - os: ubuntu-latest
            rust: nightly
          - os: windows
            rust: stable
          - os: windows
            rust: nightly

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        ci/ubuntu-install-packages

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
